export const images = {
    avo_buuble: require('./img/avo_bubble.png'),
    avo_bubble_error: require('./img/avo_bubble_error.png'),
    badge_green: require('./img/badge_green.png'),
    badge_white: require('./img/badge_white.png'),
    tick: require('./img/tick.png'),
    white_warning: require('./img/warning.png'),
    drag_handle_dark: require('./img/drag_handle_dark.png'),
    drag_handle_light: require('./img/drag_handle_light.png'),
    avo_logo: require('./img/avo_logo.png'),
    close_button: require('./img/close_button.png'),
    collapse_arrow: require('./img/collapse_arrow.png'),
    expend_arrow: require('./img/expend_arrow.png'),
    red_warning: require('./img/red_warning.png'),
}